name: Ubuntu CI

on:
  push:

  pull_request:
    branches:
      - master

jobs:
  build:
    name: "Ubuntu latest: g++"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libblas-dev liblapack-dev libeigen3-dev libboost-all-dev

      - name: Build and Test
        run: |
          cmake -H. -B build
          cmake --build build
          ./bin/test_davidson
